# Generated by Django 2.2.6 on 2021-02-03 08:02

import apps.posts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0011_auto_20201214_1422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='slug',
            field=models.SlugField(help_text='Укажите псевдоним сообщества', verbose_name='Слаг'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, help_text='Выберите изображение к сообщению', null=True, upload_to=apps.posts.models.author_directory_path, verbose_name='Изображение'),
        ),
    ]
